#Jekyll Configuration
title: DHK Digital
description: A portfolio and blog site displaying the work by Dudley Harvey-Kelly.
url: "http://dudleyhk.github.io"
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-slate
